name: Run and Test Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask requests

    - name: Start the app
      run: |
        nohup python app.py > app.log 2>&1 &
        sleep 10  # Wait for the server to start

    - name: Check endpoint
      run: |
        STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/random-megumin)
        if [ "$STATUS_CODE" -ne 200 ]; then
          echo "Error: Endpoint returned status code $STATUS_CODE"
          cat app.log  # Output the server logs for debugging
          exit 1
        fi
